metadata:
  name: bootstrap

resources:
- applications/argo-workflows.yaml
- applications/argo-artifacts.yaml
- applications/argo-rollouts.yaml
- applications/argo-events.yaml
- applications/gitea.yaml

patches:
- path: patches/patch-application-common.yaml
  target:
    kind: Application